<?php
declare(strict_types=1);
require_once __DIR__.'/bootstrap.php';

function require_admin_page(): array {
  $u=current_user();
  if(!$u){header('Location: /admin/login.php');exit;}
  if($u['role']!=='admin'){http_response_code(403);exit('Administrator access required.');}
  return $u;
}

function admin_svg(string $name): string {
  $icons=[
    'bolt'=>'<polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>',
    'grid'=>'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
    'layers'=>'<path d="m12 3 9 5-9 5-9-5 9-5Z"/><path d="m3 12 9 5 9-5M3 16l9 5 9-5"/>',
    'orders'=>'<path d="M8 4h11v17H5V7z"/><path d="M8 3v4M16 3v4M5 10h14M8 14h8M8 17h5"/>',
    'users'=>'<path d="M16 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="10" cy="7" r="4"/><path d="M20 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',
    'payments'=>'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18M7 15h4"/>',
    'chart'=>'<path d="M3 3v18h18"/><path d="m7 14 4-4 4 3 6-7"/>',
    'globe'=>'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"/>',
    'mail'=>'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>',
    'logout'=>'<path d="M10 17l5-5-5-5M15 12H3"/><path d="M12 3h6a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-6"/>',
    'menu'=>'<path d="M4 6h16M4 12h16M4 18h16"/>',
  ];
  $body=$icons[$name]??$icons['grid'];
  return '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">'.$body.'</svg>';
}

function admin_header(string $active,string $title): void {
  $user=require_admin_page();
  header('Content-Type: text/html; charset=utf-8');
  header('Cache-Control: no-store, private');
  $safeTitle=htmlspecialchars($title,ENT_QUOTES,'UTF-8');
  $safeName=htmlspecialchars((string)$user['name'],ENT_QUOTES,'UTF-8');
  $initial=strtoupper(substr((string)$user['name'],0,1));
  $links=[
    ['overview','/admin/?tab=overview','Overview','grid'],
    ['services','/admin/?tab=services','Service controllers','layers'],
    ['orders','/admin/?tab=orders','Orders','orders'],
    ['customers','/admin/?tab=customers','Customers','users'],
    ['payments','/admin/?tab=payments','Payments','payments'],
    ['fx','/admin/?tab=fx','Payment FX rates','chart'],
  ];
  echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="dark"><title>'.$safeTitle.' · TDC Tech Admin</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet"><style>
:root{--bg:#09090b;--bg2:#0f0f14;--bg3:#141420;--bg4:#1a1a2e;--surface:rgba(255,255,255,.04);--surface-soft:rgba(255,255,255,.025);--line:rgba(255,255,255,.08);--line2:rgba(99,102,241,.28);--ink:#f4f4f5;--sub:#a1a1aa;--muted:#71717a;--accent:#6366f1;--cyan:#22d3ee;--purple:#a855f7;--green:#4ade80;--red:#f87171;--orange:#fb923c;--grad:linear-gradient(135deg,#6366f1,#22d3ee);--grad2:linear-gradient(135deg,#a855f7,#6366f1);--glow:0 0 40px rgba(99,102,241,.18);--shadow:0 18px 45px rgba(0,0,0,.2)}
*,*::before,*::after{box-sizing:border-box}html{min-height:100%;background:var(--bg);scroll-behavior:smooth}body{margin:0;min-height:100%;background:var(--bg);color:var(--ink);font:14px Inter,ui-sans-serif,system-ui,sans-serif;-webkit-font-smoothing:antialiased;overflow-x:hidden}body::before{content:"";position:fixed;inset:0;pointer-events:none;z-index:0;background-image:url("data:image/svg+xml,%3Csvg viewBox=%270 0 256 256%27 xmlns=%27http://www.w3.org/2000/svg%27%3E%3Cfilter id=%27noise%27%3E%3CfeTurbulence type=%27fractalNoise%27 baseFrequency=%270.9%27 numOctaves=%274%27 stitchTiles=%27stitchTiles%27/%3E%3C/filter%3E%3Crect width=%27100%25%27 height=%27100%25%27 filter=%27url(%23noise)%27 opacity=%270.03%27/%3E%3C/svg%3E");opacity:.35}button,input,textarea,select{font:inherit}button{cursor:pointer}a{color:#a5b4fc}::-webkit-scrollbar{width:5px;height:5px}::-webkit-scrollbar-track{background:var(--bg2)}::-webkit-scrollbar-thumb{background:rgba(99,102,241,.4);border-radius:5px}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.35}}
.admin-shell{position:relative;z-index:1;min-height:100vh}.sidebar{position:fixed;inset:0 auto 0 0;width:232px;background:var(--bg2);color:var(--text);padding:20px 12px 14px;display:flex;flex-direction:column;z-index:30;border-right:1px solid var(--line);overflow-y:auto}.brand-lockup{display:flex;align-items:center;gap:9px;padding:0 8px 24px;color:var(--ink);text-decoration:none}.brand-mark{width:30px;height:30px;border-radius:8px;background:var(--grad);display:grid;place-items:center;color:#fff;box-shadow:0 0 18px rgba(99,102,241,.28)}.brand-mark svg{width:14px;height:14px;stroke:#fff;fill:none;stroke-width:2.5}.brand-name{display:flex;align-items:center;gap:7px;font-size:.9rem;font-weight:800;letter-spacing:-.02em}.admin-badge{font-size:.56rem;font-weight:800;letter-spacing:.1em;color:#fbbf24;background:rgba(251,191,36,.12);border:1px solid rgba(251,191,36,.28);padding:3px 7px;border-radius:100px}.side-profile{display:flex;align-items:center;gap:10px;padding:11px 10px;margin:0 2px 18px;border:1px solid var(--line);border-radius:10px;background:var(--surface)}.avatar{width:31px;height:31px;flex:0 0 auto;border-radius:50%;display:grid;place-items:center;background:var(--grad);border:2px solid rgba(255,255,255,.12);color:#fff;font-size:11px;font-weight:800}.side-profile strong{display:block;color:var(--ink);font-size:10px;max-width:145px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.side-profile small{display:block;color:var(--muted);font-size:9px;margin-top:3px}.side-label{padding:9px 10px 5px;margin:0;color:var(--muted);font-size:.6rem;font-weight:700;text-transform:uppercase;letter-spacing:.09em}.side-nav{display:grid;gap:2px}.side-nav a,.side-action{display:flex;align-items:center;gap:10px;min-height:38px;padding:8px 10px;border:1px solid transparent;border-radius:9px;color:var(--muted);text-decoration:none;font-size:.78rem;font-weight:500;transition:all .15s}.side-nav a svg,.side-action svg{width:15px;height:15px;flex:0 0 15px}.side-nav a:hover,.side-action:hover{background:var(--surface);color:var(--ink)}.side-nav a.active{background:rgba(99,102,241,.15);color:#a5b4fc;border-color:rgba(99,102,241,.14)}.sidebar-spacer{flex:1;min-height:16px}.side-divider{height:1px;margin:12px 8px;background:var(--line)}.side-action{width:100%;background:transparent;cursor:pointer;text-align:left}.side-action.danger:hover{color:#f87171;background:rgba(248,113,113,.07)}
.main{min-height:100vh;margin-left:232px}.topbar{height:68px;position:sticky;top:0;z-index:15;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:0 28px;background:rgba(9,9,11,.9);border-bottom:1px solid var(--line);backdrop-filter:blur(14px)}.crumb{color:var(--muted);font-size:.65rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em}.crumb strong{color:var(--sub);font-weight:700}.top-user{display:flex;align-items:center;gap:9px;color:var(--sub);font-size:.72rem;font-weight:600}.top-user .avatar{width:32px;height:32px}.menu-toggle{display:none;width:36px;height:36px;align-items:center;justify-content:center;border:1px solid var(--line);border-radius:8px;background:var(--surface);color:var(--sub);cursor:pointer}.menu-toggle:hover{color:var(--ink);border-color:rgba(255,255,255,.16)}.menu-toggle svg{width:18px;height:18px}.page-wrap{max-width:1550px;margin:0 auto;padding:24px 28px 48px}.page-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:16px;margin:0 0 22px}.page-heading h1{margin:0;color:var(--ink);font-size:1.35rem;line-height:1.25;letter-spacing:-.035em;font-weight:800}.page-heading p{margin:6px 0 0;color:var(--muted);font-size:.76rem;line-height:1.55}.page-heading .eyebrow{display:flex;align-items:center;gap:6px;margin-bottom:7px;color:#a5b4fc;font-size:.6rem;font-weight:800;text-transform:uppercase;letter-spacing:.1em}.page-heading .eyebrow::before{content:"";width:7px;height:7px;border-radius:50%;background:var(--green);animation:pulse 1.6s infinite}.notice{min-height:0;margin:0 0 10px;color:var(--green);font-size:.74rem}.notice:empty{display:none}.notice.error{color:var(--red)}
.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:0 0 20px}.stat{position:relative;min-height:108px;padding:16px;background:var(--surface);border:1px solid var(--line);border-radius:13px;overflow:hidden}.stat:first-child{background:linear-gradient(135deg,rgba(99,102,241,.14),rgba(34,211,238,.06));border-color:var(--line2)}.stat span{display:flex;align-items:center;justify-content:space-between;gap:6px;color:var(--muted);font-size:.66rem;font-weight:700;letter-spacing:.035em;text-transform:uppercase}.stat strong{display:block;margin-top:11px;color:var(--ink);font-size:1.45rem;font-weight:900;letter-spacing:-.04em}.stat:first-child strong{background:var(--grad);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}.stat small{display:block;margin-top:5px;color:var(--muted);font-size:.66rem}.panel,.card{padding:18px;background:var(--surface);border:1px solid var(--line);border-radius:13px;box-shadow:none}.panel{margin:0 0 14px}.panel:hover,.card:hover{border-color:rgba(99,102,241,.18)}.panel h2{margin:0 0 15px;color:var(--ink);font-size:.86rem;font-weight:700;letter-spacing:-.015em}.panel h3,.card h3{color:var(--ink)}.muted{color:var(--muted);font-size:.7rem;line-height:1.6}.empty{padding:24px;color:var(--muted);text-align:center;font-size:.74rem}.toolbar{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.toolbar h2{margin:0}.btn,.tab{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:34px;padding:0 11px;border:1px solid var(--line);border-radius:8px;background:var(--surface);color:var(--sub);cursor:pointer;font-size:.7rem;font-weight:650;text-decoration:none;transition:all .15s}.btn:hover,.tab:hover{background:rgba(255,255,255,.07);border-color:rgba(255,255,255,.16);color:var(--ink)}.btn.primary{border-color:transparent;background:var(--grad);color:#fff;box-shadow:0 0 20px rgba(99,102,241,.2)}.btn.primary:hover{opacity:.9;box-shadow:0 0 28px rgba(99,102,241,.32)}.btn.danger{color:#f87171;border-color:rgba(248,113,113,.25);background:rgba(248,113,113,.07)}.btn.small{min-height:28px;padding:0 9px;font-size:.65rem}.nav{display:flex;gap:6px;flex-wrap:wrap}.tab.active{color:#a5b4fc;background:rgba(99,102,241,.15);border-color:rgba(99,102,241,.3)}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:10px}.service-card{display:flex;align-items:center;gap:12px;min-height:76px;padding:14px;background:var(--surface);border:1px solid var(--line);border-radius:12px;color:inherit;text-decoration:none;transition:all .2s cubic-bezier(.16,1,.3,1)}.service-card:hover{border-color:var(--line2);box-shadow:var(--glow);transform:translateY(-2px)}.service-icon{width:38px;height:38px;flex:0 0 38px;display:grid;place-items:center;border-radius:9px;background:rgba(99,102,241,.14);color:#a5b4fc}.service-icon svg{width:18px;height:18px}.service-card strong{display:block;color:var(--ink);font-size:.75rem;font-weight:700}.service-card small{display:block;color:var(--muted);font-size:.64rem;margin-top:5px}
.table-wrap{width:100%;overflow:auto}table{width:100%;border-collapse:collapse;min-width:680px}th,td{padding:11px 10px;text-align:left;border-bottom:1px solid rgba(255,255,255,.05);vertical-align:top}th{color:var(--muted);font-size:.62rem;text-transform:uppercase;letter-spacing:.065em;font-weight:700;white-space:nowrap}td{color:var(--sub);font-size:.71rem;line-height:1.5}td strong{color:var(--ink)}tbody tr:hover{background:rgba(255,255,255,.02)}tbody tr:last-child td{border-bottom:0}.badge{display:inline-flex;align-items:center;padding:4px 8px;border-radius:100px;background:rgba(99,102,241,.13);border:1px solid rgba(99,102,241,.2);color:#a5b4fc;font-size:.62rem;font-weight:700}.row-actions{display:flex;gap:6px;flex-wrap:wrap}.input,select,textarea{width:100%;padding:9px 10px;background:var(--bg2);border:1px solid var(--line);border-radius:8px;color:var(--ink);font-size:.72rem;outline:none}.input:focus,select:focus,textarea:focus{border-color:rgba(99,102,241,.5);box-shadow:0 0 0 3px rgba(99,102,241,.09)}select option{background:var(--bg3);color:var(--ink)}textarea::placeholder,input::placeholder{color:#5e5e68}.input.short{width:118px}.form-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:13px}.field label{display:block;margin:0 0 6px;color:var(--muted);font-size:.66rem;font-weight:700;letter-spacing:.025em}.split{display:grid;grid-template-columns:1.5fr 1fr;gap:14px}.analytics-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.chart-title{display:flex;justify-content:space-between;align-items:center;margin:4px 2px 9px;color:var(--sub);font-size:.7rem}.chart-title strong{font-size:.72rem;color:var(--ink)}.overview-lower{display:grid;grid-template-columns:1.65fr 1fr;gap:14px}.service-table-icon{display:inline-grid;place-items:center;vertical-align:middle;width:27px;height:27px;margin-right:8px;background:rgba(99,102,241,.14);color:#a5b4fc;border-radius:7px}.service-table-icon svg{width:14px;height:14px}.status-row{display:grid;grid-template-columns:9px 1fr auto;align-items:center;gap:9px;padding:10px 0;border-bottom:1px solid rgba(255,255,255,.05)}.status-row:last-child{border-bottom:0}.state-dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#71717a;vertical-align:middle;margin-right:5px}.state-dot.on{background:var(--green)}.state-dot.off{background:#71717a}.status-name{color:var(--sub);font-size:.7rem;text-transform:capitalize}.status-row strong{font-size:.7rem;color:var(--ink)}.status-track{grid-column:1/-1;height:4px;margin-top:-3px;background:rgba(255,255,255,.07);border-radius:9px;overflow:hidden}.status-track i{display:block;height:100%;border-radius:9px}.chart{display:block;width:100%;height:210px;background:rgba(0,0,0,.12);border:1px solid var(--line);border-radius:10px}.hidden{display:none!important}.sidebar-scrim{display:none}.section-label{margin:21px 0 9px;color:var(--muted);font-size:.62rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em}
@media(max-width:1100px){.stats{grid-template-columns:repeat(2,minmax(0,1fr))}.overview-lower{grid-template-columns:1fr}.page-wrap{padding-left:22px;padding-right:22px}.topbar{padding:0 22px}}
@media(max-width:820px){.analytics-grid{grid-template-columns:1fr}.sidebar{transform:translateX(-101%);transition:transform .2s ease;box-shadow:16px 0 45px rgba(0,0,0,.45)}.sidebar.open{transform:translateX(0)}.sidebar-scrim.visible{display:block;position:fixed;inset:0;background:rgba(0,0,0,.68);backdrop-filter:blur(3px);z-index:25}.main{margin-left:0}.menu-toggle{display:inline-flex}.topbar{justify-content:flex-start;padding:0 16px}.top-user{margin-left:auto}.page-wrap{padding:20px 16px 34px}.split{grid-template-columns:1fr}}
@media(max-width:520px){.topbar{height:58px}.crumb{font-size:.58rem}.top-user>span:last-child{display:none}.page-heading{align-items:flex-start;flex-direction:column;margin-bottom:18px}.page-heading h1{font-size:1.18rem}.stats{grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.stat{min-height:94px;padding:13px}.stat strong{font-size:1.22rem;margin-top:10px}.panel,.card{padding:14px}.grid{grid-template-columns:1fr}.toolbar{align-items:flex-start}.form-grid{grid-template-columns:1fr}.chart{height:185px}}
</style></head><body><div class="admin-shell"><aside class="sidebar" id="admin-sidebar"><a class="brand-lockup" href="/admin/"><span class="brand-mark">'.admin_svg('bolt').'</span><span class="brand-name">TDC Tech <span class="admin-badge">ADMIN</span></span></a><div class="side-profile"><span class="avatar">'.htmlspecialchars($initial,ENT_QUOTES,'UTF-8').'</span><span><strong>'.$safeName.'</strong><small>Administrator · Private panel</small></span></div><div class="side-label">Workspace</div><nav class="side-nav" aria-label="Admin navigation">';
  foreach($links as [$key,$href,$label,$icon]){
    $isActive=$active===$key?' active':'';
    echo '<a class="side-link'.$isActive.'" data-sidebar-tab="'.$key.'" href="'.$href.'">'.admin_svg($icon).'<span>'.$label.'</span></a>';
  }
  echo '</nav><div class="sidebar-spacer"></div><div class="side-label">Platform</div><nav class="side-nav" aria-label="Site management"><a class="side-link'.($active==='content'?' active':'').'" href="/admin/content.php">'.admin_svg('globe').'<span>Website content</span></a><a class="side-link'.($active==='emails'?' active':'').'" href="/admin/emails.php">'.admin_svg('mail').'<span>Email notifications</span></a></nav><div class="side-divider"></div><button class="side-action danger" id="admin-logout" type="button">'.admin_svg('logout').'<span>Sign out</span></button></aside><div class="sidebar-scrim" id="sidebar-scrim"></div><main class="main"><header class="topbar"><button class="menu-toggle" id="menu-toggle" type="button" aria-label="Open admin navigation" aria-expanded="false">'.admin_svg('menu').'</button><div class="crumb">TDC TECH <span aria-hidden="true">/</span> <strong>'.$safeTitle.'</strong></div><div class="top-user"><span class="avatar">'.htmlspecialchars($initial,ENT_QUOTES,'UTF-8').'</span><span>'.$safeName.'</span></div></header><div class="page-wrap"><div class="page-heading"><div><span class="eyebrow">Admin control center</span><h1>'.$safeTitle.'</h1><p>Track every service, customer, order, payment, and platform operation.</p></div></div><div class="notice" id="notice" role="status"></div>';
  echo '<script>(function(){const side=document.getElementById("admin-sidebar"),scrim=document.getElementById("sidebar-scrim"),toggle=document.getElementById("menu-toggle");function close(){side.classList.remove("open");scrim.classList.remove("visible");toggle.setAttribute("aria-expanded","false")}toggle.addEventListener("click",()=>{const open=side.classList.toggle("open");scrim.classList.toggle("visible",open);toggle.setAttribute("aria-expanded",String(open))});scrim.addEventListener("click",close);document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});document.querySelectorAll(".side-link").forEach(a=>a.addEventListener("click",close));document.getElementById("admin-logout").addEventListener("click",async()=>{const c=await fetch("/api/csrf.php",{credentials:"same-origin"}).then(r=>r.json());await fetch("/api/auth.php",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json","X-CSRF-Token":c.csrf},body:JSON.stringify({action:"logout"})});location.href="/admin/login.php"})})();</script>';
}

function admin_footer(): void {echo '</div></main></div></body></html>';}
