<?php
require dirname(__DIR__,2).'/app/bootstrap.php';
$u=current_user();if(!$u){header('Location: /login.php');exit;}if($u['role']!=='admin'){http_response_code(403);exit('Access denied.');}
header('Content-Type: text/html; charset=utf-8');header('Cache-Control: no-store, private');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin · TDC Tech</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>
:root{--bg:#09090b;--panel:#12121a;--card:#171720;--border:#ffffff14;--text:#f4f4f5;--sub:#a1a1aa;--muted:#71717a;--indigo:#6366f1;--cyan:#22d3ee}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px Inter,system-ui,sans-serif}.shell{max-width:1440px;margin:auto;padding:28px}.head{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:26px}.head h1{font-size:1.65rem;margin:0 0 5px}.head p{margin:0;color:var(--sub)}.actions{display:flex;gap:10px}.btn,.tab{border:1px solid var(--border);border-radius:9px;background:#ffffff08;color:var(--text);padding:10px 14px;cursor:pointer;font:600 .84rem Inter}.btn:hover,.tab:hover{border-color:#6366f177}.btn.primary{background:var(--indigo);border-color:var(--indigo)}.stats{display:grid;grid-template-columns:repeat(5,minmax(120px,1fr));gap:12px;margin-bottom:20px}.stat,.panel{background:var(--panel);border:1px solid var(--border);border-radius:14px;padding:17px}.stat span{color:var(--muted);font-size:.75rem}.stat strong{display:block;font-size:1.55rem;margin-top:8px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.tab.active{background:#6366f133;border-color:#6366f177;color:#c7d2fe}.panel h2{font-size:1.05rem;margin:0 0 14px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:680px}th,td{padding:11px 10px;text-align:left;border-bottom:1px solid var(--border);vertical-align:middle}th{color:var(--muted);font-size:.72rem;text-transform:uppercase;letter-spacing:.04em}td{font-size:.83rem}.badge{padding:4px 8px;border-radius:99px;background:#6366f122;color:#c7d2fe;font-size:.72rem}.row-actions{display:flex;gap:6px;flex-wrap:wrap}.small{font-size:.74rem;padding:7px 9px}.input{width:94px;padding:8px;background:#09090b;border:1px solid var(--border);border-radius:7px;color:white}.notice{min-height:22px;color:#86efac;padding:3px 0 8px}.empty{color:var(--muted);padding:20px 0}.danger{color:#fca5a5}.hidden{display:none!important}@media(max-width:850px){.stats{grid-template-columns:repeat(2,1fr)}.shell{padding:18px}.head{align-items:flex-start;flex-direction:column}}
</style></head><body><main class="shell"><header class="head"><div><h1>TDC Tech Admin</h1><p>Manage orders, customers, payment status, FX rates, and service pricing.</p></div><div class="actions"><a class="btn" href="/dashboard.php" style="text-decoration:none">Customer dashboard</a><button class="btn" id="logout">Sign out</button></div></header><div class="notice" id="notice" role="status"></div><section class="stats" id="stats"></section><nav class="tabs"><button class="tab active" data-tab="orders">Orders</button><button class="tab" data-tab="topups">Payments</button><button class="tab" data-tab="fx">FX rates</button><button class="tab" data-tab="users">Customers</button><button class="tab" data-tab="services">Services & prices</button></nav><section class="panel"><h2 id="panel-title">Orders</h2><div id="content" class="table-wrap"></div></section></main><script>
let data=null,current='orders';const content=document.getElementById('content'),notice=document.getElementById('notice');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(){const r=await fetch('/api/admin.php',{credentials:'same-origin',cache:'no-store'});if(r.status===401||r.status===403){location.href='/login.php';return;}data=await r.json();drawStats();draw();}
function drawStats(){const x=data.stats;document.getElementById('stats').innerHTML=[['Customers',x.users],['Orders',x.orders],['Pending orders',x.pending_orders],['Top-ups to review',x.pending_topups],['Wallet debits','£'+Number(x.revenue).toFixed(2)]].map(v=>`<div class="stat"><span>${v[0]}</span><strong>${v[1]}</strong></div>`).join('');}
function draw(){document.getElementById('panel-title').textContent=({orders:'Orders',topups:'Gateway payments',fx:'Payment currency rates',users:'Customers',services:'Service catalogue'})[current];if(current==='orders')orders();if(current==='topups')topups();if(current==='fx')fxRates();if(current==='users')users();if(current==='services')services();}
function orders(){content.innerHTML=data.orders.length?`<table><thead><tr><th>Order</th><th>Customer</th><th>Service</th><th>Amount</th><th>Status</th><th>Placed</th><th>Change status</th><th>Admin note</th></tr></thead><tbody>${data.orders.map(o=>`<tr><td>#${o.id}</td><td>${esc(o.name)}<br><span style="color:#71717a">${esc(o.email)}</span></td><td>${esc(o.description||o.service)}</td><td>£${Number(o.amount).toFixed(2)}</td><td><span class="badge">${esc(o.status)}</span></td><td>${esc(o.created_at)}</td><td><select class="input" id="os-${o.id}"><option ${o.status==='pending'?'selected':''}>pending</option><option ${o.status==='processing'?'selected':''}>processing</option><option ${o.status==='completed'?'selected':''}>completed</option><option ${o.status==='rejected'?'selected':''}>rejected</option><option ${o.status==='cancelled'?'selected':''}>cancelled</option></select><button class="btn small" onclick="changeOrder(${o.id})">Save status</button></td><td><textarea id="on-${o.id}" class="input" style="width:210px;height:58px" maxlength="4000" placeholder="Customer-visible fulfillment note">${esc(o.admin_note||'')}</textarea><button class="btn small" onclick="saveNote(${o.id})">Save note</button></td></tr>`).join('')}</tbody></table>`:'<p class="empty">No orders yet.</p>';}
function topups(){content.innerHTML=data.topups.length?`<table><thead><tr><th>Customer</th><th>Wallet credit</th><th>Provider amount</th><th>Gateway</th><th>Status</th><th>Reference</th><th>Created</th></tr></thead><tbody>${data.topups.map(t=>`<tr><td>${esc(t.customer)}<br><span style="color:#71717a">${esc(t.email)}</span></td><td>£${Number(t.amount).toFixed(2)}</td><td>${Number(t.provider_amount).toFixed(2)} ${esc(t.currency)}</td><td>${esc(t.gateway)}</td><td><span class="badge">${esc(t.status)}</span></td><td>${esc(t.provider_reference||t.local_reference)}</td><td>${esc(t.created_at)}</td></tr>`).join('')}</tbody></table>`:'<p class="empty">No payment attempts yet.</p>';}
function fxRates(){content.innerHTML=`<table><thead><tr><th>Currency</th><th>Units per £1</th><th>Enabled</th><th>Save</th></tr></thead><tbody>${data.fx.map(x=>`<tr><td>${esc(x.currency)}</td><td><input class="input" style="width:150px" id="fx-${x.currency}" type="number" min="0.000001" step="0.000001" value="${Number(x.units_per_gbp)}"></td><td><input id="fa-${x.currency}" type="checkbox" ${x.active?'checked':''}></td><td><button class="btn small" onclick="saveFx('${x.currency}')">Save rate</button></td></tr>`).join('')}</tbody></table><p class="empty">Set provider currency units for £1 using your chosen current rate source. Payments stay disabled until a valid rate is saved and enabled. The gateway key remains in server configuration.</p>`;}
function users(){content.innerHTML=data.users.length?`<table><thead><tr><th>Customer</th><th>Balance</th><th>Status</th><th>Joined</th><th>Actions</th></tr></thead><tbody>${data.users.map(u=>`<tr><td>${esc(u.name)}<br><span style="color:#71717a">${esc(u.email)}</span></td><td>£${Number(u.balance).toFixed(2)}</td><td><span class="badge">${esc(u.status)}</span></td><td>${esc(u.created_at)}</td><td><div class="row-actions"><button class="btn small" onclick="adjust(${u.id})">Adjust wallet</button><button class="btn small" onclick="status(${u.id},'${u.status==='active'?'suspended':'active'}')">${u.status==='active'?'Suspend':'Reactivate'}</button></div></td></tr>`).join('')}</tbody></table>`:'<p class="empty">No customer accounts yet.</p>';}
function services(){content.innerHTML=`<table><thead><tr><th>Service</th><th>Slug</th><th>Price GBP</th><th>Available</th><th>Update</th></tr></thead><tbody>${data.services.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.slug)}</td><td><input class="input" id="sp-${s.id}" type="number" min="0" step="0.01" value="${Number(s.price).toFixed(2)}"></td><td><input id="sa-${s.id}" type="checkbox" ${s.active?'checked':''}></td><td><button class="btn small" onclick="saveService(${s.id})">Save</button></td></tr>`).join('')}</tbody></table><p class="empty">Prices are validated by the backend. Payment gateway credentials are not stored here.</p>`;}
async function post(action,values){const r=await fetch('/api/admin.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':data.csrf},body:JSON.stringify({action,...values})});const x=await r.json();if(!r.ok)throw new Error(x.error||'Action failed.');return x;}
async function run(action,values,msg){try{await post(action,values);notice.textContent=msg;await load();}catch(e){notice.textContent=e.message;notice.className='notice danger';}}
function saveFx(currency){run('fx_update',{currency,units_per_gbp:document.getElementById('fx-'+currency).value,active:document.getElementById('fa-'+currency).checked},'Currency rate updated.');}
function changeOrder(id){run('order_status',{id,status:document.getElementById('os-'+id).value},'Order updated.');}
function saveNote(id){run('order_note',{id,note:document.getElementById('on-'+id).value},'Fulfillment note saved for this customer.');}
function status(id,status){run('user_status',{id,status},'Customer account updated.');}
function adjust(id){const amount=prompt('Adjustment amount in GBP. Use a negative number to debit:');if(amount===null)return;const note=prompt('Reason for this wallet adjustment:');if(note===null)return;run('wallet_adjust',{id,amount,note},'Wallet ledger updated.');}
function saveService(id){run('service_update',{id,price:document.getElementById('sp-'+id).value,active:document.getElementById('sa-'+id).checked},'Service updated.');}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.tab.active')?.classList.remove('active');b.classList.add('active');current=b.dataset.tab;draw();}));
document.getElementById('logout').onclick=async()=>{try{await fetch('/api/auth.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':data.csrf},body:JSON.stringify({action:'logout'})});}finally{location.href='/';}};
load();
</script></body></html>
