<?php
require dirname(__DIR__,2).'/app/admin_view.php';admin_header('overview','Private admin workspace');
?>
<section class="stats" id="stats"></section>
<nav class="nav" id="tabs" style="margin:14px 0"><button class="tab active" data-tab="overview">Overview</button><button class="tab" data-tab="services">Service controllers</button><button class="tab" data-tab="orders">Orders</button><button class="tab" data-tab="customers">Customers</button><button class="tab" data-tab="payments">Payments</button><button class="tab" data-tab="fx">Payment FX rates</button></nav>
<section class="panel"><h2 id="panel-title">Overview</h2><div id="content" class="table-wrap"><p class="muted">Loading admin workspace…</p></div></section>
<script>
let adminData=null,workspace=null,csrf='';let current='overview';const content=document.getElementById('content'),notice=document.getElementById('notice');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(){try{const [a,w]=await Promise.all([fetch('/api/admin.php',{credentials:'same-origin',cache:'no-store'}),fetch('/api/admin-console.php',{credentials:'same-origin',cache:'no-store'})]);if(a.status===401||a.status===403||w.status===401||w.status===403){location.href='/admin/login.php';return;}adminData=await a.json();workspace=await w.json();csrf=adminData.csrf;drawStats();draw();}catch(e){content.textContent='Unable to load admin workspace.';}}
function drawStats(){const x=workspace.stats;document.getElementById('stats').innerHTML=[['Customers',x.users],['Orders',x.orders],['Requests to review',x.requests],['Wallet revenue','£'+Number(x.revenue).toFixed(2)],['Active controllers',workspace.pages.filter(p=>Number(p.active)).length]].map(v=>`<div class="stat"><span>${v[0]}</span><strong>${v[1]}</strong></div>`).join('');}
function draw(){document.getElementById('panel-title').textContent=({overview:'Overview',services:'Service controllers',orders:'Orders',customers:'Customers',payments:'Gateway payments',fx:'Payment FX rates'})[current];({overview,services:drawServices,orders:drawOrders,customers:drawCustomers,payments:drawPayments,fx:drawFx})[current]();}
function overview(){content.innerHTML=`<p class="muted">Each dashboard service has its own page for requests, orders, publication status, pricing, income, and analytics. Website text, branding, partnerships, team members, brand icons, and testimonials are managed from Website content. Email events queue automatically and are sent by the SMTP worker after you add credentials.</p><div class="grid">${workspace.pages.map(p=>`<a class="service-card" href="/admin/service.php?slug=${encodeURIComponent(p.slug)}"><span class="service-icon">${esc(p.icon)}</span><span><strong>${esc(p.name)}</strong><small>${Number(p.orders_count)} orders · £${Number(p.revenue).toFixed(2)} revenue</small></span></a>`).join('')}</div>`;}
function drawServices(){content.innerHTML=`<div class="grid">${workspace.pages.map(p=>`<a class="service-card" href="/admin/service.php?slug=${encodeURIComponent(p.slug)}"><span class="service-icon">${esc(p.icon)}</span><span><strong>${esc(p.name)}</strong><small>${esc(p.slug)} · ${Number(p.orders_count)} orders</small></span></a>`).join('')}</div><h3 style="margin-top:24px">Priced catalog items</h3><div class="table-wrap"><table><thead><tr><th>Service</th><th>Route group</th><th>Price</th><th>Active</th><th>Controller</th></tr></thead><tbody>${adminData.services.map(s=>{const p=workspace.pages.find(p=>p.slug===s.slug)||workspace.pages.find(p=>({ 'template-nexus':'web-dev','template-storefront':'web-dev','template-vibe':'web-dev','account-social':'account-mgmt','account-publicist':'account-mgmt','account-youtube':'account-mgmt','account-meta':'account-mgmt','account-dmca':'account-mgmt','press-tier1':'press','press-tier2':'press','wiki-tier1':'press','wiki-tier2':'press','smm-followers':'smm','smm-likes':'smm','smm-views':'smm','smm-comments':'smm'})[s.slug]===p.slug);return `<tr><td>${esc(s.name)}<br><small class="muted">${esc(s.slug)}</small></td><td>${esc(p?.name||'Unmapped')}</td><td>£${Number(s.price).toFixed(2)} ${esc(s.pricing_mode)}</td><td>${s.active?'Yes':'No'}</td><td>${p?`<a href="/admin/service.php?slug=${encodeURIComponent(p.slug)}">Open controller</a>`:'—'}</td></tr>`;}).join('')}</tbody></table></div>`;}
function drawOrders(){content.innerHTML=adminData.orders.length?`<table><thead><tr><th>Order</th><th>Customer</th><th>Service</th><th>Amount</th><th>Status</th><th>Placed</th><th>Actions</th></tr></thead><tbody>${adminData.orders.map(o=>`<tr><td>#${o.id}</td><td>${esc(o.name)}<br><small class="muted">${esc(o.email)}</small></td><td>${esc(o.service)}<br><small class="muted">${esc(o.description)}</small></td><td>£${Number(o.amount).toFixed(2)}</td><td><span class="badge">${esc(o.status)}</span></td><td>${esc(o.created_at)}</td><td><a href="/admin/service.php?slug=${encodeURIComponent(o.admin_page_slug||'')}">Open service controller</a><br><select id="os-${o.id}" class="input short"><option>pending</option><option>processing</option><option>completed</option><option>rejected</option><option>cancelled</option></select> <button class="btn small" onclick="orderStatus(${o.id})">Save</button></td></tr>`).join('')}</tbody></table>`:'<p class="empty">No orders yet.</p>';}
function drawCustomers(){content.innerHTML=adminData.users.length?`<table><thead><tr><th>Customer</th><th>Wallet</th><th>Status</th><th>Joined</th><th>Actions</th></tr></thead><tbody>${adminData.users.map(u=>`<tr><td>${esc(u.name)}<br><small class="muted">${esc(u.email)}</small></td><td>£${Number(u.balance).toFixed(2)}</td><td><span class="badge">${esc(u.status)}</span></td><td>${esc(u.created_at)}</td><td><button class="btn small" onclick="adjust(${u.id})">Adjust wallet</button> <button class="btn small" onclick="userStatus(${u.id},'${u.status==='active'?'suspended':'active'}')">${u.status==='active'?'Suspend':'Reactivate'}</button></td></tr>`).join('')}</tbody></table>`:'<p class="empty">No customer accounts yet.</p>';}
function drawPayments(){content.innerHTML=adminData.topups.length?`<table><thead><tr><th>Customer</th><th>Wallet credit</th><th>Provider amount</th><th>Gateway</th><th>Status</th><th>Reference</th><th>Date</th></tr></thead><tbody>${adminData.topups.map(t=>`<tr><td>${esc(t.customer)}<br><small class="muted">${esc(t.email)}</small></td><td>£${Number(t.amount).toFixed(2)}</td><td>${Number(t.provider_amount).toFixed(2)} ${esc(t.currency)}</td><td>${esc(t.gateway)}</td><td><span class="badge">${esc(t.status)}</span></td><td>${esc(t.provider_reference||t.local_reference)}</td><td>${esc(t.created_at)}</td></tr>`).join('')}</tbody></table>`:'<p class="empty">No gateway payments yet.</p>';}
function drawFx(){content.innerHTML=`<p class="muted">Provider payment currencies map to the GBP wallet using these administrator-managed units per £1. Set a current rate from your chosen source. A currency stays unavailable until its rate is enabled.</p><table><thead><tr><th>Currency</th><th>Units per £1</th><th>Enabled</th><th>Update</th></tr></thead><tbody>${adminData.fx.map(x=>`<tr><td>${esc(x.currency)}</td><td><input class="input short" id="fx-${x.currency}" type="number" step="0.000001" min="0.000001" value="${Number(x.units_per_gbp)}"></td><td><input id="fa-${x.currency}" type="checkbox" ${x.active?'checked':''}></td><td><button class="btn small" onclick="saveFx('${x.currency}')">Save</button></td></tr>`).join('')}</tbody></table>`;}
async function post(url,payload){const r=await fetch(url,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Action failed.');return d;}
async function run(action,values,msg,url='/api/admin.php'){try{await post(url,{action,...values});notice.textContent=msg;notice.className='notice';await load();}catch(e){notice.textContent=e.message;notice.className='notice error';}}
function orderStatus(id){run('order_status',{id,status:document.getElementById('os-'+id).value},'Order updated.');}
function userStatus(id,status){run('user_status',{id,status},'Customer updated.');}
function adjust(id){const amount=prompt('Wallet adjustment amount in GBP (negative debits):');if(amount===null)return;const note=prompt('Reason for adjustment:');if(note===null)return;run('wallet_adjust',{id,amount,note},'Wallet updated.');}
function saveFx(currency){run('fx_update',{currency,units_per_gbp:document.getElementById('fx-'+currency).value,active:document.getElementById('fa-'+currency).checked},'Currency rate updated.');}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelector('.tab.active')?.classList.remove('active');b.classList.add('active');current=b.dataset.tab;draw();});load();
</script>
<?php admin_footer(); ?>
