<?php
require dirname(__DIR__,2).'/app/admin_view.php';admin_header('overview','Admin overview');
?>
<section class="stats" id="stats" aria-label="Key business metrics"></section>
<section class="panel" id="overview-panel"><div class="toolbar" style="justify-content:space-between;margin-bottom:14px"><div><h2 style="margin:0">Business performance</h2><p class="muted" style="margin:5px 0 0">Orders and net service income over the last 30 days</p></div><span class="badge">Last 30 days</span></div><div class="analytics-grid"><div><div class="chart-title"><strong>Orders received</strong><span id="orders-total" class="muted"></span></div><div id="orders-chart"></div></div><div><div class="chart-title"><strong>Net income</strong><span id="income-total" class="muted"></span></div><div id="income-chart"></div></div></div></section>
<div class="overview-lower" id="overview-lower"><section class="panel"><div class="toolbar" style="justify-content:space-between"><h2>Service performance</h2><a class="btn small" href="/admin/?tab=services">All controllers</a></div><div class="table-wrap" id="service-summary"></div></section><section class="panel"><h2>Order status</h2><div id="status-summary"></div></section></div>
<section class="panel" id="recent-panel"><div class="toolbar" style="justify-content:space-between"><h2>Latest orders</h2><a class="btn small" href="/admin/?tab=orders">View all orders</a></div><div class="table-wrap" id="recent-orders"></div></section>
<section id="section-content" class="panel hidden"><div id="content"></div></section>
<script>
let adminData=null,workspace=null,csrf='',current=new URLSearchParams(location.search).get('tab')||'overview';const content=document.getElementById('content'),notice=document.getElementById('notice');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'£'+Number(n||0).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});
function serviceIcon(slug){const paths={social:'<path d="m3 11 18-5-5 18-4-8-9-5Z"/><path d="m12 16 5-5"/>',music:'<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>',verify:'<path d="M12 3 4 6v5c0 5 3.5 8.4 8 10 4.5-1.6 8-5 8-10V6l-8-3Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/>',web:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M8 9v11"/>',account:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',press:'<path d="M4 4h16v16H4zM8 8h8M8 12h8M8 16h5"/>',smm:'<path d="M20.8 8.6c0 4.4-8.8 10-8.8 10s-8.8-5.6-8.8-10A4.6 4.6 0 0 1 12 6.3a4.6 4.6 0 0 1 8.8 2.3Z"/>',phone:'<rect x="6" y="2.5" width="12" height="19" rx="2"/><path d="M10 18.5h4"/>',bot:'<rect x="4" y="7" width="16" height="13" rx="3"/><path d="M12 3v4M9 13h.01M15 13h.01M9 17h6"/><path d="M2 12v3M22 12v3"/>',proxy:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.5 2.5 3.5 5.5 3.5 9s-1 6.5-3.5 9c-2.5-2.5-3.5-5.5-3.5-9s1-6.5 3.5-9Z"/>'};const key=({"social-ads":"social",music:"music",verification:"verify","web-dev":"web","account-mgmt":"account",press:"press",smm:"smm",numbers:"phone",bots:"bot",proxies:"proxy"})[slug]||'web';return `<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${paths[key]}</svg>`;}
async function load(){try{const [a,w]=await Promise.all([fetch('/api/admin.php',{credentials:'same-origin',cache:'no-store'}),fetch('/api/admin-console.php',{credentials:'same-origin',cache:'no-store'})]);if(a.status===401||a.status===403||w.status===401||w.status===403){location.href='/admin/login.php';return;}if(!a.ok||!w.ok)throw new Error('Admin data could not be loaded.');adminData=await a.json();workspace=await w.json();csrf=adminData.csrf;drawStats();drawOverview();setSection(current,false);}catch(e){document.getElementById('overview-panel').innerHTML=`<p class="empty">${esc(e.message||'Unable to load admin workspace.')}</p>`;}}
function drawStats(){const x=workspace.stats;const cards=[['Customers',Number(x.users).toLocaleString('en-GB'),'Registered customer accounts'],['Orders',Number(x.orders).toLocaleString('en-GB'),`${Number(x.pending_orders)} need review`],['Net income',money(x.revenue),'Service orders after refunds'],['Fulfillment rate',`${Number(x.completion_rate||0)}%`,'Orders completed']];document.getElementById('stats').innerHTML=cards.map(([label,value,hint])=>`<article class="stat"><span>${label}</span><strong>${value}</strong><small>${hint}</small></article>`).join('');}
function svgBars(values){const W=720,H=190,L=28,R=8,T=12,B=27,inner=W-L-R,base=H-B,max=Math.max(1,...values.map(x=>Number(x.orders_count)));const bw=inner/values.length*.56,gap=inner/values.length;let bars=values.map((x,i)=>{const n=Number(x.orders_count),h=Math.max(n?2:0,n/max*135),xx=L+i*gap+(gap-bw)/2;return `<rect x="${xx.toFixed(1)}" y="${(base-h).toFixed(1)}" width="${bw.toFixed(1)}" height="${h.toFixed(1)}" rx="3" fill="#625bf4"><title>${esc(x.day)}: ${n} orders</title></rect>`}).join('');const lines=[0,.5,1].map(t=>{const y=T+t*138;return `<line x1="${L}" y1="${y}" x2="${W-R}" y2="${y}" stroke="#edf0f5"/>`}).join('');const ticks=[0,7,14,21,29].map(i=>`<text x="${L+i*gap+gap/2}" y="${H-7}" text-anchor="middle" fill="#98a2b3" font-size="9">${esc(String(values[i]?.day||'').slice(5))}</text>`).join('');return `<svg class="chart" role="img" aria-label="Daily orders for the last 30 days" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${lines}${bars}${ticks}</svg>`;}
function svgIncome(values){const W=720,H=190,L=42,R=10,T=14,B=28,inner=W-L-R,base=H-B,max=Math.max(1,...values.map(x=>Math.abs(Number(x.income))));let points=values.map((x,i)=>{const n=Number(x.income),px=L+i*inner/Math.max(1,values.length-1),py=94-(n/max)*68;return [px,py,n,x.day]});const line=points.map(p=>p[0].toFixed(1)+','+p[1].toFixed(1)).join(' ');const area=`${L},94 ${line} ${W-R},94`;const lines=[0,.5,1].map(t=>{const y=T+t*132;return `<line x1="${L}" y1="${y}" x2="${W-R}" y2="${y}" stroke="#edf0f5"/>`}).join('');const ticks=[0,7,14,21,29].map(i=>`<text x="${L+i*inner/29}" y="${H-7}" text-anchor="middle" fill="#98a2b3" font-size="9">${esc(String(values[i]?.day||'').slice(5))}</text>`).join('');return `<svg class="chart" role="img" aria-label="Daily net income for the last 30 days" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${lines}<polygon points="${area}" fill="#4f46e5" fill-opacity=".09"/><polyline points="${line}" fill="none" stroke="#4f46e5" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round"/>${points.filter((_,i)=>i%5===0||i===points.length-1).map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="3" fill="#4f46e5"><title>${esc(p[3])}: ${money(p[2])}</title></circle>`).join('')}${ticks}</svg>`;}
function drawOverview(){const trend=workspace.analytics.trend||[];const totals=trend.reduce((a,x)=>({orders:a.orders+Number(x.orders_count),income:a.income+Number(x.income)}),{orders:0,income:0});document.getElementById('orders-total').textContent=totals.orders+' orders';document.getElementById('income-total').textContent=money(totals.income);document.getElementById('orders-chart').innerHTML=svgBars(trend);document.getElementById('income-chart').innerHTML=svgIncome(trend);
const pages=workspace.pages||[];document.getElementById('service-summary').innerHTML=`<table><thead><tr><th>Service</th><th>Orders</th><th>Net income</th><th>Availability</th><th></th></tr></thead><tbody>${pages.slice().sort((a,b)=>Number(b.revenue)-Number(a.revenue)).slice(0,6).map(p=>`<tr><td><span class="service-table-icon">${serviceIcon(p.slug)}</span><strong>${esc(p.name)}</strong></td><td>${Number(p.orders_count)}</td><td>${money(p.revenue)}</td><td>${Number(p.active)?'<span class="state-dot on"></span> Active':'<span class="state-dot off"></span> Hidden'}</td><td><a href="/admin/service.php?slug=${encodeURIComponent(p.slug)}">Manage</a></td></tr>`).join('')}</tbody></table>`;
const statuses=workspace.analytics.statuses||[];const colors={pending:'#d99124',processing:'#4d78c5',completed:'#16835b',rejected:'#c2414b',cancelled:'#8a94a5'};document.getElementById('status-summary').innerHTML=statuses.length?statuses.map(s=>`<div class="status-row"><span class="state-dot" style="background:${colors[s.status]||'#98a2b3'}"></span><span class="status-name">${esc(s.status)}</span><strong>${Number(s.count)}</strong><div class="status-track"><i style="width:${Math.min(100,Number(s.percent))}%;background:${colors[s.status]||'#98a2b3'}"></i></div></div>`).join(''):'<p class="empty">No order activity yet.</p>';
document.getElementById('recent-orders').innerHTML=adminData.orders.length?`<table><thead><tr><th>Order</th><th>Customer</th><th>Service</th><th>Amount</th><th>Status</th><th>Received</th></tr></thead><tbody>${adminData.orders.slice(0,5).map(o=>`<tr><td>#${o.id}</td><td>${esc(o.customer)}</td><td>${esc(o.service)}</td><td>${money(o.amount)}</td><td><span class="badge">${esc(o.status)}</span></td><td>${esc(o.created_at)}</td></tr>`).join('')}</tbody></table>`:'<p class="empty">No orders have been received yet.</p>';}
function setSection(tab,push=true){if(!['overview','services','orders','customers','payments','fx'].includes(tab))tab='overview';current=tab;if(push){const u=new URL(location.href);u.searchParams.set('tab',tab);history.pushState({tab},'',u);}document.querySelectorAll('[data-sidebar-tab]').forEach(a=>a.classList.toggle('active',a.dataset.sidebarTab===tab));document.getElementById('stats').classList.toggle('hidden',tab!=='overview');document.getElementById('overview-panel').classList.toggle('hidden',tab!=='overview');document.getElementById('overview-lower').classList.toggle('hidden',tab!=='overview');document.getElementById('recent-panel').classList.toggle('hidden',tab!=='overview');document.getElementById('section-content').classList.toggle('hidden',tab==='overview');if(tab!=='overview'){content.innerHTML='<p class="empty">Loading section…</p>';({services:drawServices,orders:drawOrders,customers:drawCustomers,payments:drawPayments,fx:drawFx})[tab]();document.querySelector('.page-heading h1').textContent=({services:'Service controllers',orders:'Orders',customers:'Customers',payments:'Gateway payments',fx:'Payment FX rates'})[tab];document.querySelector('.page-heading p').textContent=({services:'Review the performance and settings for every customer-facing service.',orders:'Track fulfillment, update order notes, and notify customers.',customers:'Review customer accounts, wallet balances, and account status.',payments:'Monitor Xdigitex Pay deposits and settlement status.',fx:'Manage the currency rates used for wallet top-ups.'})[tab];}else{document.querySelector('.page-heading h1').textContent='Admin overview';document.querySelector('.page-heading p').textContent='Monitor service delivery, customer activity, and income.';}}
function drawServices(){content.innerHTML=`<div class="grid">${workspace.pages.map(p=>`<a class="service-card" href="/admin/service.php?slug=${encodeURIComponent(p.slug)}"><span class="service-icon">${serviceIcon(p.slug)}</span><span><strong>${esc(p.name)}</strong><small>${Number(p.orders_count)} orders · ${money(p.revenue)} net income</small></span></a>`).join('')}</div><h3 class="section-label">Catalog items</h3><div class="table-wrap"><table><thead><tr><th>Service</th><th>Route group</th><th>Price</th><th>Active</th><th>Controller</th></tr></thead><tbody>${adminData.services.map(s=>{const group={'template-nexus':'web-dev','template-storefront':'web-dev','template-vibe':'web-dev','account-social':'account-mgmt','account-publicist':'account-mgmt','account-youtube':'account-mgmt','account-meta':'account-mgmt','account-dmca':'account-mgmt','press-tier1':'press','press-tier2':'press','wiki-tier1':'press','wiki-tier2':'press','smm-followers':'smm','smm-likes':'smm','smm-views':'smm','smm-comments':'smm'}[s.slug]||s.slug;const p=workspace.pages.find(x=>x.slug===group);return `<tr><td>${esc(s.name)}<br><small class="muted">${esc(s.slug)}</small></td><td>${esc(p?.name||'Unmapped')}</td><td>${money(s.price)} <span class="muted">${esc(s.pricing_mode)}</span></td><td>${Number(s.active)?'Active':'Paused'}</td><td>${p?`<a href="/admin/service.php?slug=${encodeURIComponent(p.slug)}">Open</a>`:'—'}</td></tr>`;}).join('')}</tbody></table></div>`;}
function drawOrders(){content.innerHTML=adminData.orders.length?`<table><thead><tr><th>Order</th><th>Customer</th><th>Service</th><th>Amount</th><th>Status</th><th>Fulfillment note</th><th>Received</th><th>Update</th></tr></thead><tbody>${adminData.orders.map(o=>`<tr><td>#${o.id}</td><td>${esc(o.customer)}<br><small class="muted">${esc(o.email)}</small></td><td>${esc(o.service)}<br><small class="muted">${esc(o.description)}</small></td><td>${money(o.amount)}</td><td><select id="os-${o.id}" class="input"><option value="pending" ${o.status==='pending'?'selected':''}>Pending</option><option value="processing" ${o.status==='processing'?'selected':''}>Processing</option><option value="completed" ${o.status==='completed'?'selected':''}>Completed</option><option value="rejected" ${o.status==='rejected'?'selected':''}>Rejected</option><option value="cancelled" ${o.status==='cancelled'?'selected':''}>Cancelled</option></select></td><td><textarea id="note-${o.id}" rows="2" maxlength="4000" placeholder="Customer-visible order update">${esc(o.admin_note||'')}</textarea></td><td>${esc(o.created_at)}</td><td><div class="row-actions"><button class="btn small" onclick="orderStatus(${o.id})">Save status</button><button class="btn small" onclick="orderNote(${o.id})">Save note</button><a class="btn small" href="/admin/service.php?slug=${encodeURIComponent(o.admin_page_slug||'')}">Service page</a></div></td></tr>`).join('')}</tbody></table>`:'<p class="empty">No orders yet.</p>';}
function drawCustomers(){content.innerHTML=adminData.users.length?`<table><thead><tr><th>Customer</th><th>Wallet balance</th><th>Account</th><th>Joined</th><th>Actions</th></tr></thead><tbody>${adminData.users.map(u=>`<tr><td><strong>${esc(u.name)}</strong><br><small class="muted">${esc(u.email)}</small></td><td>${money(u.balance)}</td><td><span class="badge">${esc(u.status)}</span></td><td>${esc(u.created_at)}</td><td><div class="row-actions"><button class="btn small" onclick="adjust(${u.id})">Adjust wallet</button><button class="btn small" onclick="userStatus(${u.id},'${u.status==='active'?'suspended':'active'}')">${u.status==='active'?'Suspend':'Reactivate'}</button></div></td></tr>`).join('')}</tbody></table>`:'<p class="empty">No customer accounts yet.</p>';}
function drawPayments(){content.innerHTML=adminData.topups.length?`<table><thead><tr><th>Customer</th><th>Wallet credit</th><th>Provider amount</th><th>Gateway</th><th>Status</th><th>Reference</th><th>Date</th></tr></thead><tbody>${adminData.topups.map(t=>`<tr><td>${esc(t.customer)}<br><small class="muted">${esc(t.email)}</small></td><td>${money(t.amount)}</td><td>${Number(t.provider_amount).toLocaleString('en-GB')} ${esc(t.currency)}</td><td>${esc(t.gateway)}</td><td><span class="badge">${esc(t.status)}</span></td><td>${esc(t.provider_reference||t.local_reference)}</td><td>${esc(t.created_at)}</td></tr>`).join('')}</tbody></table>`:'<p class="empty">No gateway payments yet.</p>';}
function drawFx(){content.innerHTML=`<p class="muted">Set the units per GBP for each supported payment currency. A currency remains unavailable until its rate is enabled.</p><table><thead><tr><th>Currency</th><th>Units per £1</th><th>Enabled</th><th>Update</th></tr></thead><tbody>${adminData.fx.map(x=>`<tr><td><strong>${esc(x.currency)}</strong></td><td><input class="input short" id="fx-${x.currency}" type="number" step="0.000001" min="0.000001" value="${Number(x.units_per_gbp)}"></td><td><input id="fa-${x.currency}" type="checkbox" ${Number(x.active)?'checked':''}></td><td><button class="btn small" onclick="saveFx('${x.currency}')">Save rate</button></td></tr>`).join('')}</tbody></table>`;}
async function post(url,payload){const r=await fetch(url,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Action failed.');return d;}
async function run(action,values,msg,url='/api/admin.php'){try{await post(url,{action,...values});notice.textContent=msg;notice.className='notice';await load();}catch(e){notice.textContent=e.message;notice.className='notice error';}}
function orderStatus(id){run('order_status',{id,status:document.getElementById('os-'+id).value},'Order status updated.');}function orderNote(id){run('order_note',{id,note:document.getElementById('note-'+id).value},'Order note updated.');}function userStatus(id,status){run('user_status',{id,status},'Customer account updated.');}
function adjust(id){const amount=prompt('Wallet adjustment amount in GBP (negative debits):');if(amount===null)return;const note=prompt('Reason for adjustment:');if(note===null)return;run('wallet_adjust',{id,amount,note},'Wallet updated.');}function saveFx(currency){run('fx_update',{currency,units_per_gbp:document.getElementById('fx-'+currency).value,active:document.getElementById('fa-'+currency).checked},'Currency rate updated.');}
document.querySelectorAll('[data-sidebar-tab]').forEach(a=>{a.addEventListener('click',e=>{e.preventDefault();setSection(a.dataset.sidebarTab);});});window.addEventListener('popstate',()=>setSection(new URLSearchParams(location.search).get('tab')||'overview',false));
load();
</script>
<?php admin_footer(); ?>
